# Generated by Django 5.2.1 on 2025-05-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('text', models.TextField()),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('attack', models.PositiveIntegerField(default=0)),
                ('defense', models.PositiveIntegerField(default=0)),
                ('card_type', models.CharField(choices=[('Monster', 'Monster'), ('Spell', 'Spell'), ('Trap', 'Trap')], db_index=True, max_length=10)),
                ('attribute', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Earth', 'Earth'), ('Water', 'Water'), ('Fire', 'Fire'), ('Wind', 'Wind'), ('Divine', 'Divine')], db_index=True, max_length=10)),
                ('rarity', models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Super Rare', 'Super Rare'), ('Ultra Rare', 'Ultra Rare'), ('Secret Rare', 'Secret Rare')], db_index=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='pages_card_name_bdf461_idx'), models.Index(fields=['card_type'], name='pages_card_card_ty_1fd885_idx'), models.Index(fields=['attribute'], name='pages_card_attribu_3420b6_idx'), models.Index(fields=['rarity'], name='pages_card_rarity_d61371_idx')],
            },
        ),
    ]
